Completed high-level FS and migrated FuseLink.
Implemented and tested high-level FS.
Implemented all Python functions for high-level FS.
Included POSIX test suite.
Added documentation for all high-level FS functions.
Added new exception classes.
Updated FuseLink to use high-level FS.
Updated test suite bootstrap tool.
Enabled C++11 support in compiler configuration.
Fixed .clang_complete settings.
Fixed FSFile to ignore requests when bad / fail flags set.
Fixed FSFile to not unintentionally clear bad / fail flags.
Removed old macros.

diff --git a/appfs/tests/config b/appfs/tests/config
--- a/appfs/tests/config
+++ b/appfs/tests/config
@@ -18,19 +18,46 @@ if [ ! -d "$DIR_WORKING" ]; then
 	mkdir -pv "$DIR_WORKING"
 fi
 
+# Ensure the test suite will run correctly.
+if [ $UID -ne 0 ]; then
+    echo "Please run the test suite as root (due to permission test requirements)."
+    exit 1
+fi
+
 if [ "$IGNORE_MOUNTING" != "true" ]; then
-	# Forcibly unmount the existing mount directory.
-	sudo umount -lf "$DIR_MOUNT" >/dev/null 2>/dev/null;
+    # Check build root is set.
+    if [[ $BUILD_ROOT && ${BUILD_ROOT-x} ]]; then
+        # All good.
+        true
+    else
+        echo "Please invoke this script with BUILD_ROOT set, like so:"
+        echo "  > BUILD_ROOT=path/of/build $0"
+        exit 1
+    fi
+
+	# Define cleanup.
+	cleanup()
+	{
+		# Forcibly unmount the existing mount directory.
+		fusermount -u "$DIR_MOUNT" >/dev/null 2>/dev/null;
+	}
+	trap cleanup SIGINT
+	cleanup
 	
 	# Ensure the mount directory exists.
-	mkdir -pv "$DIR_MOUNT"
+    if [ ! -d "$DIR_MOUNT" ]; then
+    	mkdir -pv "$DIR_MOUNT"
+    else
+        # Ensure it is empty.
+        rm -R "$DIR_MOUNT/"
+        mkdir -pv "$DIR_MOUNT"
+    fi
 	
 	# Remove and recreate the test package.
 	rm "$FILE_AFS"
-	"$DIR_ROOT/appcreate" "$FILE_AFS"
+	"$BUILD_ROOT/appfs/appcreate" "$FILE_AFS"
 	
 	# Wait for the user to signal that AppMount has started.
-	echo "Press enter when you have started AppMount using the following parameters:"
-	echo "  $FILE_AFS $DIR_MOUNT"
-	read -n 1 -s
+	"$BUILD_ROOT/appfs/appmount" -o "$FILE_AFS" "$DIR_MOUNT" &
+	sleep 1
 fi
